//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrimaveraResultStructure", Namespace="http://schemas.datacontract.org/2004/07/MIT.WCF_Services")]
    [System.SerializableAttribute()]
    public partial class PrimaveraResultStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.Stream ficheiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string procedimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subNivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoProblemaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codeLevel {
            get {
                return this.codeLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.codeLevelField, value) != true)) {
                    this.codeLevelField = value;
                    this.RaisePropertyChanged("codeLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.Stream ficheiro {
            get {
                return this.ficheiroField;
            }
            set {
                if ((object.ReferenceEquals(this.ficheiroField, value) != true)) {
                    this.ficheiroField = value;
                    this.RaisePropertyChanged("ficheiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string procedimento {
            get {
                return this.procedimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.procedimentoField, value) != true)) {
                    this.procedimentoField = value;
                    this.RaisePropertyChanged("procedimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subNivel {
            get {
                return this.subNivelField;
            }
            set {
                if ((object.ReferenceEquals(this.subNivelField, value) != true)) {
                    this.subNivelField = value;
                    this.RaisePropertyChanged("subNivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoProblema {
            get {
                return this.tipoProblemaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoProblemaField, value) != true)) {
                    this.tipoProblemaField = value;
                    this.RaisePropertyChanged("tipoProblema");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Moeda", Namespace="http://schemas.datacontract.org/2004/07/MIT.WCF_Services")]
    [System.SerializableAttribute()]
    public partial class Moeda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string moedaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moeda {
            get {
                return this.moedaField;
            }
            set {
                if ((object.ReferenceEquals(this.moedaField, value) != true)) {
                    this.moedaField = value;
                    this.RaisePropertyChanged("moeda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service_MIT_MotoresErp.IMIT_MotoresErp")]
    public interface IMIT_MotoresErp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIT_MotoresErp/AbreEmpresaPrimavera", ReplyAction="http://tempuri.org/IMIT_MotoresErp/AbreEmpresaPrimaveraResponse")]
        MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.PrimaveraResultStructure AbreEmpresaPrimavera(int tipoPlataforma, string codEmpresa, string codUsuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIT_MotoresErp/AbreEmpresaPrimavera", ReplyAction="http://tempuri.org/IMIT_MotoresErp/AbreEmpresaPrimaveraResponse")]
        System.Threading.Tasks.Task<MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.PrimaveraResultStructure> AbreEmpresaPrimaveraAsync(int tipoPlataforma, string codEmpresa, string codUsuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIT_MotoresErp/Empresa_Moedas", ReplyAction="http://tempuri.org/IMIT_MotoresErp/Empresa_MoedasResponse")]
        MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.Moeda[] Empresa_Moedas(int tipoPlataforma, string codEmpresa, string codUsuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIT_MotoresErp/Empresa_Moedas", ReplyAction="http://tempuri.org/IMIT_MotoresErp/Empresa_MoedasResponse")]
        System.Threading.Tasks.Task<MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.Moeda[]> Empresa_MoedasAsync(int tipoPlataforma, string codEmpresa, string codUsuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIT_MotoresErp/Pendentes_Gravar_Diferencas_Cambio", ReplyAction="http://tempuri.org/IMIT_MotoresErp/Pendentes_Gravar_Diferencas_CambioResponse")]
        MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.PrimaveraResultStructure Pendentes_Gravar_Diferencas_Cambio(int tipoPlataforma, string codEmpresa, string codUsuario, string password, string docDiferencaPositivos, string docDiferencasNegativos, double valor, string entidade, string tipoEntidade, string moeda, System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIT_MotoresErp/Pendentes_Gravar_Diferencas_Cambio", ReplyAction="http://tempuri.org/IMIT_MotoresErp/Pendentes_Gravar_Diferencas_CambioResponse")]
        System.Threading.Tasks.Task<MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.PrimaveraResultStructure> Pendentes_Gravar_Diferencas_CambioAsync(int tipoPlataforma, string codEmpresa, string codUsuario, string password, string docDiferencaPositivos, string docDiferencasNegativos, double valor, string entidade, string tipoEntidade, string moeda, System.DateTime data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMIT_MotoresErpChannel : MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.IMIT_MotoresErp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MIT_MotoresErpClient : System.ServiceModel.ClientBase<MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.IMIT_MotoresErp>, MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.IMIT_MotoresErp {
        
        public MIT_MotoresErpClient() {
        }
        
        public MIT_MotoresErpClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MIT_MotoresErpClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MIT_MotoresErpClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MIT_MotoresErpClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.PrimaveraResultStructure AbreEmpresaPrimavera(int tipoPlataforma, string codEmpresa, string codUsuario, string password) {
            return base.Channel.AbreEmpresaPrimavera(tipoPlataforma, codEmpresa, codUsuario, password);
        }
        
        public System.Threading.Tasks.Task<MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.PrimaveraResultStructure> AbreEmpresaPrimaveraAsync(int tipoPlataforma, string codEmpresa, string codUsuario, string password) {
            return base.Channel.AbreEmpresaPrimaveraAsync(tipoPlataforma, codEmpresa, codUsuario, password);
        }
        
        public MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.Moeda[] Empresa_Moedas(int tipoPlataforma, string codEmpresa, string codUsuario, string password) {
            return base.Channel.Empresa_Moedas(tipoPlataforma, codEmpresa, codUsuario, password);
        }
        
        public System.Threading.Tasks.Task<MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.Moeda[]> Empresa_MoedasAsync(int tipoPlataforma, string codEmpresa, string codUsuario, string password) {
            return base.Channel.Empresa_MoedasAsync(tipoPlataforma, codEmpresa, codUsuario, password);
        }
        
        public MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.PrimaveraResultStructure Pendentes_Gravar_Diferencas_Cambio(int tipoPlataforma, string codEmpresa, string codUsuario, string password, string docDiferencaPositivos, string docDiferencasNegativos, double valor, string entidade, string tipoEntidade, string moeda, System.DateTime data) {
            return base.Channel.Pendentes_Gravar_Diferencas_Cambio(tipoPlataforma, codEmpresa, codUsuario, password, docDiferencaPositivos, docDiferencasNegativos, valor, entidade, tipoEntidade, moeda, data);
        }
        
        public System.Threading.Tasks.Task<MIT.Aplicacoes.CCT_Processamento_Diferencas_Cambio.Service_MIT_MotoresErp.PrimaveraResultStructure> Pendentes_Gravar_Diferencas_CambioAsync(int tipoPlataforma, string codEmpresa, string codUsuario, string password, string docDiferencaPositivos, string docDiferencasNegativos, double valor, string entidade, string tipoEntidade, string moeda, System.DateTime data) {
            return base.Channel.Pendentes_Gravar_Diferencas_CambioAsync(tipoPlataforma, codEmpresa, codUsuario, password, docDiferencaPositivos, docDiferencasNegativos, valor, entidade, tipoEntidade, moeda, data);
        }
    }
}
