//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primavera.WPF_Application_Test.ServicePrimavera {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contactos", Namespace="http://schemas.datacontract.org/2004/07/Primavera.WebServices.Services")]
    [System.SerializableAttribute()]
    public partial class Contactos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailAlternativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailPrincipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string localidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string moradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nrTelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nrTelefoneAlternativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primeiroNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ultimoNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailAlternativo {
            get {
                return this.emailAlternativoField;
            }
            set {
                if ((object.ReferenceEquals(this.emailAlternativoField, value) != true)) {
                    this.emailAlternativoField = value;
                    this.RaisePropertyChanged("emailAlternativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailPrincipal {
            get {
                return this.emailPrincipalField;
            }
            set {
                if ((object.ReferenceEquals(this.emailPrincipalField, value) != true)) {
                    this.emailPrincipalField = value;
                    this.RaisePropertyChanged("emailPrincipal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string localidade {
            get {
                return this.localidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.localidadeField, value) != true)) {
                    this.localidadeField = value;
                    this.RaisePropertyChanged("localidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string morada {
            get {
                return this.moradaField;
            }
            set {
                if ((object.ReferenceEquals(this.moradaField, value) != true)) {
                    this.moradaField = value;
                    this.RaisePropertyChanged("morada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeCompleto {
            get {
                return this.nomeCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeCompletoField, value) != true)) {
                    this.nomeCompletoField = value;
                    this.RaisePropertyChanged("nomeCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrTelefone {
            get {
                return this.nrTelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.nrTelefoneField, value) != true)) {
                    this.nrTelefoneField = value;
                    this.RaisePropertyChanged("nrTelefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrTelefoneAlternativo {
            get {
                return this.nrTelefoneAlternativoField;
            }
            set {
                if ((object.ReferenceEquals(this.nrTelefoneAlternativoField, value) != true)) {
                    this.nrTelefoneAlternativoField = value;
                    this.RaisePropertyChanged("nrTelefoneAlternativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primeiroNome {
            get {
                return this.primeiroNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.primeiroNomeField, value) != true)) {
                    this.primeiroNomeField = value;
                    this.RaisePropertyChanged("primeiroNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoContacto {
            get {
                return this.tipoContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoContactoField, value) != true)) {
                    this.tipoContactoField = value;
                    this.RaisePropertyChanged("tipoContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ultimoNome {
            get {
                return this.ultimoNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.ultimoNomeField, value) != true)) {
                    this.ultimoNomeField = value;
                    this.RaisePropertyChanged("ultimoNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrimaveraResultStructure", Namespace="http://schemas.datacontract.org/2004/07/Primavera.WebServices.Services")]
    [System.SerializableAttribute()]
    public partial class PrimaveraResultStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Primavera.WPF_Application_Test.ServicePrimavera.Pendente[] pedentesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string procedimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subNivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoProblemaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codeLevel {
            get {
                return this.codeLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.codeLevelField, value) != true)) {
                    this.codeLevelField = value;
                    this.RaisePropertyChanged("codeLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Primavera.WPF_Application_Test.ServicePrimavera.Pendente[] pedentes {
            get {
                return this.pedentesField;
            }
            set {
                if ((object.ReferenceEquals(this.pedentesField, value) != true)) {
                    this.pedentesField = value;
                    this.RaisePropertyChanged("pedentes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string procedimento {
            get {
                return this.procedimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.procedimentoField, value) != true)) {
                    this.procedimentoField = value;
                    this.RaisePropertyChanged("procedimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subNivel {
            get {
                return this.subNivelField;
            }
            set {
                if ((object.ReferenceEquals(this.subNivelField, value) != true)) {
                    this.subNivelField = value;
                    this.RaisePropertyChanged("subNivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoProblema {
            get {
                return this.tipoProblemaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoProblemaField, value) != true)) {
                    this.tipoProblemaField = value;
                    this.RaisePropertyChanged("tipoProblema");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pendente", Namespace="http://schemas.datacontract.org/2004/07/Primavera.WebServices.Services")]
    [System.SerializableAttribute()]
    public partial class Pendente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCriacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataVencimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double valorPendenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCriacao {
            get {
                return this.DataCriacaoField;
            }
            set {
                if ((this.DataCriacaoField.Equals(value) != true)) {
                    this.DataCriacaoField = value;
                    this.RaisePropertyChanged("DataCriacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataVencimento {
            get {
                return this.DataVencimentoField;
            }
            set {
                if ((this.DataVencimentoField.Equals(value) != true)) {
                    this.DataVencimentoField = value;
                    this.RaisePropertyChanged("DataVencimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moeda {
            get {
                return this.MoedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoedaField, value) != true)) {
                    this.MoedaField = value;
                    this.RaisePropertyChanged("Moeda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((this.NumeroDocumentoField.Equals(value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieDocumento {
            get {
                return this.SerieDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieDocumentoField, value) != true)) {
                    this.SerieDocumentoField = value;
                    this.RaisePropertyChanged("SerieDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorTotal {
            get {
                return this.ValorTotalField;
            }
            set {
                if ((this.ValorTotalField.Equals(value) != true)) {
                    this.ValorTotalField = value;
                    this.RaisePropertyChanged("ValorTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cliente {
            get {
                return this.clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.clienteField, value) != true)) {
                    this.clienteField = value;
                    this.RaisePropertyChanged("cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoDocumentoField, value) != true)) {
                    this.tipoDocumentoField = value;
                    this.RaisePropertyChanged("tipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorPendente {
            get {
                return this.valorPendenteField;
            }
            set {
                if ((this.valorPendenteField.Equals(value) != true)) {
                    this.valorPendenteField = value;
                    this.RaisePropertyChanged("valorPendente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artigo", Namespace="http://schemas.datacontract.org/2004/07/Primavera.WebServices.Services")]
    [System.SerializableAttribute()]
    public partial class Artigo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string artigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double descontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double quantidadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string artigo {
            get {
                return this.artigoField;
            }
            set {
                if ((object.ReferenceEquals(this.artigoField, value) != true)) {
                    this.artigoField = value;
                    this.RaisePropertyChanged("artigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double desconto {
            get {
                return this.descontoField;
            }
            set {
                if ((this.descontoField.Equals(value) != true)) {
                    this.descontoField = value;
                    this.RaisePropertyChanged("desconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                if ((this.quantidadeField.Equals(value) != true)) {
                    this.quantidadeField = value;
                    this.RaisePropertyChanged("quantidade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePrimavera.IPrimavera_Service")]
    public interface IPrimavera_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimavera_Service/CriarAluno", ReplyAction="http://tempuri.org/IPrimavera_Service/CriarAlunoResponse")]
        Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure CriarAluno(
                    int tipoPlataforma, 
                    string codEmpresa, 
                    string codUtilizador, 
                    string password, 
                    string cliente, 
                    string nome, 
                    string nomeFiscal, 
                    float desconto, 
                    string facMorada, 
                    string facLocalidade, 
                    string facNrTelefone, 
                    string nuit, 
                    string vendedor, 
                    string observacao, 
                    bool cdu_bolsa, 
                    bool cdu_geraMulta, 
                    string cdu_tipoIngresso, 
                    string cdu_codLic, 
                    string cdu_turma, 
                    Primavera.WPF_Application_Test.ServicePrimavera.Contactos contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimavera_Service/CriarAluno", ReplyAction="http://tempuri.org/IPrimavera_Service/CriarAlunoResponse")]
        System.Threading.Tasks.Task<Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure> CriarAlunoAsync(
                    int tipoPlataforma, 
                    string codEmpresa, 
                    string codUtilizador, 
                    string password, 
                    string cliente, 
                    string nome, 
                    string nomeFiscal, 
                    float desconto, 
                    string facMorada, 
                    string facLocalidade, 
                    string facNrTelefone, 
                    string nuit, 
                    string vendedor, 
                    string observacao, 
                    bool cdu_bolsa, 
                    bool cdu_geraMulta, 
                    string cdu_tipoIngresso, 
                    string cdu_codLic, 
                    string cdu_turma, 
                    Primavera.WPF_Application_Test.ServicePrimavera.Contactos contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimavera_Service/ActualizarAluno", ReplyAction="http://tempuri.org/IPrimavera_Service/ActualizarAlunoResponse")]
        Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure ActualizarAluno(
                    int tipoPlataforma, 
                    string codEmpresa, 
                    string codUtilizador, 
                    string password, 
                    string cliente, 
                    string novoNrCliente, 
                    string nome, 
                    string nomeFiscal, 
                    float desconto, 
                    string facMorada, 
                    string facLocalidade, 
                    string facNrTelefone, 
                    string nuit, 
                    string vendedor, 
                    string observacao, 
                    bool cdu_bolsa, 
                    bool cdu_geraMulta, 
                    string cdu_tipoIngresso, 
                    string cdu_codLic, 
                    string cdu_turma, 
                    Primavera.WPF_Application_Test.ServicePrimavera.Contactos contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimavera_Service/ActualizarAluno", ReplyAction="http://tempuri.org/IPrimavera_Service/ActualizarAlunoResponse")]
        System.Threading.Tasks.Task<Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure> ActualizarAlunoAsync(
                    int tipoPlataforma, 
                    string codEmpresa, 
                    string codUtilizador, 
                    string password, 
                    string cliente, 
                    string novoNrCliente, 
                    string nome, 
                    string nomeFiscal, 
                    float desconto, 
                    string facMorada, 
                    string facLocalidade, 
                    string facNrTelefone, 
                    string nuit, 
                    string vendedor, 
                    string observacao, 
                    bool cdu_bolsa, 
                    bool cdu_geraMulta, 
                    string cdu_tipoIngresso, 
                    string cdu_codLic, 
                    string cdu_turma, 
                    Primavera.WPF_Application_Test.ServicePrimavera.Contactos contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimavera_Service/CriarFactura", ReplyAction="http://tempuri.org/IPrimavera_Service/CriarFacturaResponse")]
        Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure CriarFactura(int tipoPlataforma, string codEmpresa, string codUtilizador, string password, string nomeUtilizador, string cliente, string tipoDoc, Primavera.WPF_Application_Test.ServicePrimavera.Artigo[] listaArtigos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimavera_Service/CriarFactura", ReplyAction="http://tempuri.org/IPrimavera_Service/CriarFacturaResponse")]
        System.Threading.Tasks.Task<Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure> CriarFacturaAsync(int tipoPlataforma, string codEmpresa, string codUtilizador, string password, string nomeUtilizador, string cliente, string tipoDoc, Primavera.WPF_Application_Test.ServicePrimavera.Artigo[] listaArtigos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimavera_Service/CriaOuActualizarContrato", ReplyAction="http://tempuri.org/IPrimavera_Service/CriaOuActualizarContratoResponse")]
        Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure CriaOuActualizarContrato(int tipoPlataforma, string codEmpresa, string codUtilizador, string password, string nomeUtilizador, string cliente, string tipoDoc, string semestreId, Primavera.WPF_Application_Test.ServicePrimavera.Artigo[] listaArtigos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimavera_Service/CriaOuActualizarContrato", ReplyAction="http://tempuri.org/IPrimavera_Service/CriaOuActualizarContratoResponse")]
        System.Threading.Tasks.Task<Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure> CriaOuActualizarContratoAsync(int tipoPlataforma, string codEmpresa, string codUtilizador, string password, string nomeUtilizador, string cliente, string tipoDoc, string semestreId, Primavera.WPF_Application_Test.ServicePrimavera.Artigo[] listaArtigos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimavera_Service/ConsultaConta", ReplyAction="http://tempuri.org/IPrimavera_Service/ConsultaContaResponse")]
        Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure ConsultaConta(int tipoPlataforma, string codEmpresa, string codUtilizador, string password, string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimavera_Service/ConsultaConta", ReplyAction="http://tempuri.org/IPrimavera_Service/ConsultaContaResponse")]
        System.Threading.Tasks.Task<Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure> ConsultaContaAsync(int tipoPlataforma, string codEmpresa, string codUtilizador, string password, string cliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrimavera_ServiceChannel : Primavera.WPF_Application_Test.ServicePrimavera.IPrimavera_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Primavera_ServiceClient : System.ServiceModel.ClientBase<Primavera.WPF_Application_Test.ServicePrimavera.IPrimavera_Service>, Primavera.WPF_Application_Test.ServicePrimavera.IPrimavera_Service {
        
        public Primavera_ServiceClient() {
        }
        
        public Primavera_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Primavera_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Primavera_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Primavera_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure CriarAluno(
                    int tipoPlataforma, 
                    string codEmpresa, 
                    string codUtilizador, 
                    string password, 
                    string cliente, 
                    string nome, 
                    string nomeFiscal, 
                    float desconto, 
                    string facMorada, 
                    string facLocalidade, 
                    string facNrTelefone, 
                    string nuit, 
                    string vendedor, 
                    string observacao, 
                    bool cdu_bolsa, 
                    bool cdu_geraMulta, 
                    string cdu_tipoIngresso, 
                    string cdu_codLic, 
                    string cdu_turma, 
                    Primavera.WPF_Application_Test.ServicePrimavera.Contactos contacto) {
            return base.Channel.CriarAluno(tipoPlataforma, codEmpresa, codUtilizador, password, cliente, nome, nomeFiscal, desconto, facMorada, facLocalidade, facNrTelefone, nuit, vendedor, observacao, cdu_bolsa, cdu_geraMulta, cdu_tipoIngresso, cdu_codLic, cdu_turma, contacto);
        }
        
        public System.Threading.Tasks.Task<Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure> CriarAlunoAsync(
                    int tipoPlataforma, 
                    string codEmpresa, 
                    string codUtilizador, 
                    string password, 
                    string cliente, 
                    string nome, 
                    string nomeFiscal, 
                    float desconto, 
                    string facMorada, 
                    string facLocalidade, 
                    string facNrTelefone, 
                    string nuit, 
                    string vendedor, 
                    string observacao, 
                    bool cdu_bolsa, 
                    bool cdu_geraMulta, 
                    string cdu_tipoIngresso, 
                    string cdu_codLic, 
                    string cdu_turma, 
                    Primavera.WPF_Application_Test.ServicePrimavera.Contactos contacto) {
            return base.Channel.CriarAlunoAsync(tipoPlataforma, codEmpresa, codUtilizador, password, cliente, nome, nomeFiscal, desconto, facMorada, facLocalidade, facNrTelefone, nuit, vendedor, observacao, cdu_bolsa, cdu_geraMulta, cdu_tipoIngresso, cdu_codLic, cdu_turma, contacto);
        }
        
        public Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure ActualizarAluno(
                    int tipoPlataforma, 
                    string codEmpresa, 
                    string codUtilizador, 
                    string password, 
                    string cliente, 
                    string novoNrCliente, 
                    string nome, 
                    string nomeFiscal, 
                    float desconto, 
                    string facMorada, 
                    string facLocalidade, 
                    string facNrTelefone, 
                    string nuit, 
                    string vendedor, 
                    string observacao, 
                    bool cdu_bolsa, 
                    bool cdu_geraMulta, 
                    string cdu_tipoIngresso, 
                    string cdu_codLic, 
                    string cdu_turma, 
                    Primavera.WPF_Application_Test.ServicePrimavera.Contactos contacto) {
            return base.Channel.ActualizarAluno(tipoPlataforma, codEmpresa, codUtilizador, password, cliente, novoNrCliente, nome, nomeFiscal, desconto, facMorada, facLocalidade, facNrTelefone, nuit, vendedor, observacao, cdu_bolsa, cdu_geraMulta, cdu_tipoIngresso, cdu_codLic, cdu_turma, contacto);
        }
        
        public System.Threading.Tasks.Task<Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure> ActualizarAlunoAsync(
                    int tipoPlataforma, 
                    string codEmpresa, 
                    string codUtilizador, 
                    string password, 
                    string cliente, 
                    string novoNrCliente, 
                    string nome, 
                    string nomeFiscal, 
                    float desconto, 
                    string facMorada, 
                    string facLocalidade, 
                    string facNrTelefone, 
                    string nuit, 
                    string vendedor, 
                    string observacao, 
                    bool cdu_bolsa, 
                    bool cdu_geraMulta, 
                    string cdu_tipoIngresso, 
                    string cdu_codLic, 
                    string cdu_turma, 
                    Primavera.WPF_Application_Test.ServicePrimavera.Contactos contacto) {
            return base.Channel.ActualizarAlunoAsync(tipoPlataforma, codEmpresa, codUtilizador, password, cliente, novoNrCliente, nome, nomeFiscal, desconto, facMorada, facLocalidade, facNrTelefone, nuit, vendedor, observacao, cdu_bolsa, cdu_geraMulta, cdu_tipoIngresso, cdu_codLic, cdu_turma, contacto);
        }
        
        public Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure CriarFactura(int tipoPlataforma, string codEmpresa, string codUtilizador, string password, string nomeUtilizador, string cliente, string tipoDoc, Primavera.WPF_Application_Test.ServicePrimavera.Artigo[] listaArtigos) {
            return base.Channel.CriarFactura(tipoPlataforma, codEmpresa, codUtilizador, password, nomeUtilizador, cliente, tipoDoc, listaArtigos);
        }
        
        public System.Threading.Tasks.Task<Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure> CriarFacturaAsync(int tipoPlataforma, string codEmpresa, string codUtilizador, string password, string nomeUtilizador, string cliente, string tipoDoc, Primavera.WPF_Application_Test.ServicePrimavera.Artigo[] listaArtigos) {
            return base.Channel.CriarFacturaAsync(tipoPlataforma, codEmpresa, codUtilizador, password, nomeUtilizador, cliente, tipoDoc, listaArtigos);
        }
        
        public Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure CriaOuActualizarContrato(int tipoPlataforma, string codEmpresa, string codUtilizador, string password, string nomeUtilizador, string cliente, string tipoDoc, string semestreId, Primavera.WPF_Application_Test.ServicePrimavera.Artigo[] listaArtigos) {
            return base.Channel.CriaOuActualizarContrato(tipoPlataforma, codEmpresa, codUtilizador, password, nomeUtilizador, cliente, tipoDoc, semestreId, listaArtigos);
        }
        
        public System.Threading.Tasks.Task<Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure> CriaOuActualizarContratoAsync(int tipoPlataforma, string codEmpresa, string codUtilizador, string password, string nomeUtilizador, string cliente, string tipoDoc, string semestreId, Primavera.WPF_Application_Test.ServicePrimavera.Artigo[] listaArtigos) {
            return base.Channel.CriaOuActualizarContratoAsync(tipoPlataforma, codEmpresa, codUtilizador, password, nomeUtilizador, cliente, tipoDoc, semestreId, listaArtigos);
        }
        
        public Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure ConsultaConta(int tipoPlataforma, string codEmpresa, string codUtilizador, string password, string cliente) {
            return base.Channel.ConsultaConta(tipoPlataforma, codEmpresa, codUtilizador, password, cliente);
        }
        
        public System.Threading.Tasks.Task<Primavera.WPF_Application_Test.ServicePrimavera.PrimaveraResultStructure> ConsultaContaAsync(int tipoPlataforma, string codEmpresa, string codUtilizador, string password, string cliente) {
            return base.Channel.ConsultaContaAsync(tipoPlataforma, codEmpresa, codUtilizador, password, cliente);
        }
    }
}
