//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebServices.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrimaveraResultStructure", Namespace="http://schemas.datacontract.org/2004/07/PRIMAVERA_ACCSYS_WCF")]
    [System.SerializableAttribute()]
    public partial class PrimaveraResultStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string procedimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subNivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoProblemaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codeLevel {
            get {
                return this.codeLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.codeLevelField, value) != true)) {
                    this.codeLevelField = value;
                    this.RaisePropertyChanged("codeLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string procedimento {
            get {
                return this.procedimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.procedimentoField, value) != true)) {
                    this.procedimentoField = value;
                    this.RaisePropertyChanged("procedimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subNivel {
            get {
                return this.subNivelField;
            }
            set {
                if ((object.ReferenceEquals(this.subNivelField, value) != true)) {
                    this.subNivelField = value;
                    this.RaisePropertyChanged("subNivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoProblema {
            get {
                return this.tipoProblemaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoProblemaField, value) != true)) {
                    this.tipoProblemaField = value;
                    this.RaisePropertyChanged("tipoProblema");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPrimavera_Accsys")]
    public interface IPrimavera_Accsys {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrimavera_Accsys/Operacao_1_Inscricao", ReplyAction="http://tempuri.org/IPrimavera_Accsys/Operacao_1_InscricaoResponse")]
        DemoWebServices.ServiceReference1.PrimaveraResultStructure Operacao_1_Inscricao(string nrEstudante, string nomeCompleto, string morada, string bairro, string nrTelefone, string nrTelefone2, string bolsa, string emailPessoal, string emailAlternativo, string tipoIngresso, string status, string observacao);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrimavera_AccsysChannel : DemoWebServices.ServiceReference1.IPrimavera_Accsys, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Primavera_AccsysClient : System.ServiceModel.ClientBase<DemoWebServices.ServiceReference1.IPrimavera_Accsys>, DemoWebServices.ServiceReference1.IPrimavera_Accsys {
        
        public Primavera_AccsysClient() {
        }
        
        public Primavera_AccsysClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Primavera_AccsysClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Primavera_AccsysClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Primavera_AccsysClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DemoWebServices.ServiceReference1.PrimaveraResultStructure Operacao_1_Inscricao(string nrEstudante, string nomeCompleto, string morada, string bairro, string nrTelefone, string nrTelefone2, string bolsa, string emailPessoal, string emailAlternativo, string tipoIngresso, string status, string observacao) {
            return base.Channel.Operacao_1_Inscricao(nrEstudante, nomeCompleto, morada, bairro, nrTelefone, nrTelefone2, bolsa, emailPessoal, emailAlternativo, tipoIngresso, status, observacao);
        }
    }
}
