'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace Service_MIT_MotoresErp
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PrimaveraResultStructure", [Namespace]:="http://schemas.datacontract.org/2004/07/MIT.WCF_Services"),  _
     System.SerializableAttribute()>  _
    Partial Public Class PrimaveraResultStructure
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private codeLevelField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private codigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private descricaoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ficheiroField As System.IO.Stream
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private procedimentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private subNivelField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private tipoProblemaField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property codeLevel() As String
            Get
                Return Me.codeLevelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codeLevelField, value) <> true) Then
                    Me.codeLevelField = value
                    Me.RaisePropertyChanged("codeLevel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property codigo() As Integer
            Get
                Return Me.codigoField
            End Get
            Set
                If (Me.codigoField.Equals(value) <> true) Then
                    Me.codigoField = value
                    Me.RaisePropertyChanged("codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property descricao() As String
            Get
                Return Me.descricaoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.descricaoField, value) <> true) Then
                    Me.descricaoField = value
                    Me.RaisePropertyChanged("descricao")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ficheiro() As System.IO.Stream
            Get
                Return Me.ficheiroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ficheiroField, value) <> true) Then
                    Me.ficheiroField = value
                    Me.RaisePropertyChanged("ficheiro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property procedimento() As String
            Get
                Return Me.procedimentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.procedimentoField, value) <> true) Then
                    Me.procedimentoField = value
                    Me.RaisePropertyChanged("procedimento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property subNivel() As String
            Get
                Return Me.subNivelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.subNivelField, value) <> true) Then
                    Me.subNivelField = value
                    Me.RaisePropertyChanged("subNivel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tipoProblema() As String
            Get
                Return Me.tipoProblemaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.tipoProblemaField, value) <> true) Then
                    Me.tipoProblemaField = value
                    Me.RaisePropertyChanged("tipoProblema")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Service_MIT_MotoresErp.IMIT_MotoresErp")>  _
    Public Interface IMIT_MotoresErp
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMIT_MotoresErp/AbreEmpresaPrimavera", ReplyAction:="http://tempuri.org/IMIT_MotoresErp/AbreEmpresaPrimaveraResponse")>  _
        Function AbreEmpresaPrimavera(ByVal tipoPlataforma As Integer, ByVal codEmpresa As String, ByVal codUsuario As String, ByVal password As String) As Service_MIT_MotoresErp.PrimaveraResultStructure
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMIT_MotoresErp/Pendentes_Gravar_Diferencas_Cambio", ReplyAction:="http://tempuri.org/IMIT_MotoresErp/Pendentes_Gravar_Diferencas_CambioResponse")>  _
        Function Pendentes_Gravar_Diferencas_Cambio(ByVal tipoPlataforma As Integer, ByVal codEmpresa As String, ByVal codUsuario As String, ByVal password As String, ByVal docDiferencaPositivos As String, ByVal docDiferencasNegativos As String, ByVal valor As Double, ByVal entidade As String, ByVal tipoEntidade As String, ByVal moeda As String, ByVal data As Date) As Service_MIT_MotoresErp.PrimaveraResultStructure
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IMIT_MotoresErpChannel
        Inherits Service_MIT_MotoresErp.IMIT_MotoresErp, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MIT_MotoresErpClient
        Inherits System.ServiceModel.ClientBase(Of Service_MIT_MotoresErp.IMIT_MotoresErp)
        Implements Service_MIT_MotoresErp.IMIT_MotoresErp
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function AbreEmpresaPrimavera(ByVal tipoPlataforma As Integer, ByVal codEmpresa As String, ByVal codUsuario As String, ByVal password As String) As Service_MIT_MotoresErp.PrimaveraResultStructure Implements Service_MIT_MotoresErp.IMIT_MotoresErp.AbreEmpresaPrimavera
            Return MyBase.Channel.AbreEmpresaPrimavera(tipoPlataforma, codEmpresa, codUsuario, password)
        End Function
        
        Public Function Pendentes_Gravar_Diferencas_Cambio(ByVal tipoPlataforma As Integer, ByVal codEmpresa As String, ByVal codUsuario As String, ByVal password As String, ByVal docDiferencaPositivos As String, ByVal docDiferencasNegativos As String, ByVal valor As Double, ByVal entidade As String, ByVal tipoEntidade As String, ByVal moeda As String, ByVal data As Date) As Service_MIT_MotoresErp.PrimaveraResultStructure Implements Service_MIT_MotoresErp.IMIT_MotoresErp.Pendentes_Gravar_Diferencas_Cambio
            Return MyBase.Channel.Pendentes_Gravar_Diferencas_Cambio(tipoPlataforma, codEmpresa, codUsuario, password, docDiferencaPositivos, docDiferencasNegativos, valor, entidade, tipoEntidade, moeda, data)
        End Function
    End Class
End Namespace
